
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by GenerateRCTThirdPartyFabricComponentsProviderCpp
 */

// OSS-compatibility layer

#import "RCTThirdPartyFabricComponentsProvider.h"

#import <string>
#import <unordered_map>

Class<RCTComponentViewProtocol> RCTThirdPartyFabricComponentsProvider(const char *name) {
  static std::unordered_map<std::string, Class (*)(void)> sFabricComponentsClassMap = {
    #if RCT_NEW_ARCH_ENABLED
    #ifndef RCT_DYNAMIC_FRAMEWORKS
#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

#if !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX

    {"BlurView", BlurViewCls}, // 4

    {"VibrancyView", VibrancyViewCls}, // 4
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

    {"RNDateTimePicker", RNDateTimePickerCls}, // 5
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

    {"RNGoogleSigninButton", RNGoogleSigninButtonCls}, // 6
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif


#if !TARGET_OS_OSX && !TARGET_OS_VISION

    {"AutoLayoutView", AutoLayoutViewCls}, // 9

    {"CellContainer", CellContainerCls}, // 9
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

    {"SkiaDomView", SkiaDomViewCls}, // 10

    {"SkiaPictureView", SkiaPictureViewCls}, // 10
#endif


    {"LottieAnimationView", LottieAnimationViewCls}, // 11
#if !TARGET_OS_OSX && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

    {"RNDatePicker", RNDatePickerCls}, // 13
#endif


#if !TARGET_OS_OSX && !TARGET_OS_VISION

    {"FastImageView", FastImageViewCls}, // 15
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_VISION

    {"RNVideoPlayer", RNVideoPlayerCls}, // 18
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif


    {"RNGestureHandlerButton", RNGestureHandlerButtonCls}, // 21

    {"RNGestureHandlerRootView", RNGestureHandlerRootViewCls}, // 21
#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

    {"RNKlarnaCheckoutView", RNKlarnaCheckoutViewCls}, // 23

    {"RNKlarnaPaymentView", RNKlarnaPaymentViewCls}, // 23

    {"RNKlarnaStandaloneWebView", RNKlarnaStandaloneWebViewCls}, // 23
#endif

#if !TARGET_OS_OSX && !TARGET_OS_VISION

    {"RNLinearGradient", RNLinearGradientCls}, // 24
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

    {"LiveStreamer", LiveStreamerCls}, // 25
#endif

#if !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV

    {"LEGACY_RNCViewPager", LEGACY_RNCViewPagerCls}, // 27

    {"RNCViewPager", RNCViewPagerCls}, // 27
#endif

#if !TARGET_OS_OSX && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

    {"ProgressCircle", ProgressCircleCls}, // 29
#endif


#if !TARGET_OS_TV

    {"RNCSafeAreaProvider", RNCSafeAreaProviderCls}, // 31

    {"RNCSafeAreaView", RNCSafeAreaViewCls}, // 31
#endif

#if !TARGET_OS_OSX && !TARGET_OS_VISION

    {"RNSFullWindowOverlay", RNSFullWindowOverlayCls}, // 32

    {"RNSModalScreen", RNSModalScreenCls}, // 32

    {"RNSScreenContainer", RNSScreenContainerCls}, // 32

    {"RNSScreen", RNSScreenCls}, // 32

    {"RNSScreenNavigationContainer", RNSScreenNavigationContainerCls}, // 32

    {"RNSScreenStackHeaderConfig", RNSScreenStackHeaderConfigCls}, // 32

    {"RNSScreenStackHeaderSubview", RNSScreenStackHeaderSubviewCls}, // 32

    {"RNSScreenStack", RNSScreenStackCls}, // 32

    {"RNSSearchBar", RNSSearchBarCls}, // 32
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif


    {"RNSVGCircle", RNSVGCircleCls}, // 34

    {"RNSVGClipPath", RNSVGClipPathCls}, // 34

    {"RNSVGDefs", RNSVGDefsCls}, // 34

    {"RNSVGEllipse", RNSVGEllipseCls}, // 34

    {"RNSVGFeBlend", RNSVGFeBlendCls}, // 34

    {"RNSVGFeColorMatrix", RNSVGFeColorMatrixCls}, // 34

    {"RNSVGFeFlood", RNSVGFeFloodCls}, // 34

    {"RNSVGFeGaussianBlur", RNSVGFeGaussianBlurCls}, // 34

    {"RNSVGFeMerge", RNSVGFeMergeCls}, // 34

    {"RNSVGFeOffset", RNSVGFeOffsetCls}, // 34

    {"RNSVGFilter", RNSVGFilterCls}, // 34

    {"RNSVGForeignObject", RNSVGForeignObjectCls}, // 34

    {"RNSVGGroup", RNSVGGroupCls}, // 34

    {"RNSVGImage", RNSVGImageCls}, // 34

    {"RNSVGSvgView", RNSVGSvgViewCls}, // 34

    {"RNSVGLinearGradient", RNSVGLinearGradientCls}, // 34

    {"RNSVGLine", RNSVGLineCls}, // 34

    {"RNSVGMarker", RNSVGMarkerCls}, // 34

    {"RNSVGMask", RNSVGMaskCls}, // 34

    {"RNSVGPath", RNSVGPathCls}, // 34

    {"RNSVGPattern", RNSVGPatternCls}, // 34

    {"RNSVGRadialGradient", RNSVGRadialGradientCls}, // 34

    {"RNSVGRect", RNSVGRectCls}, // 34

    {"RNSVGSymbol", RNSVGSymbolCls}, // 34

    {"RNSVGText", RNSVGTextCls}, // 34

    {"RNSVGTextPath", RNSVGTextPathCls}, // 34

    {"RNSVGTSpan", RNSVGTSpanCls}, // 34

    {"RNSVGUse", RNSVGUseCls}, // 34
#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

    {"VideoThumbnailsView", VideoThumbnailsViewCls}, // 35
#endif

#if !TARGET_OS_TV && !TARGET_OS_VISION

    {"RNCWebView", RNCWebViewCls}, // 36
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

    {"WindowPortalView", WindowPortalViewCls}, // 37
#endif

    #endif
    #endif
  };

  auto p = sFabricComponentsClassMap.find(name);
  if (p != sFabricComponentsClassMap.end()) {
    auto classFunc = p->second;
    return classFunc();
  }
  return nil;
}
