
/*
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by GenerateRCTThirdPartyFabricComponentsProviderH
 */

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wreturn-type-c-linkage"

#import <React/RCTComponentViewProtocol.h>

#ifdef __cplusplus
extern "C" {
#endif

Class<RCTComponentViewProtocol> RCTThirdPartyFabricComponentsProvider(const char *name);
#if RCT_NEW_ARCH_ENABLED
#ifndef RCT_DYNAMIC_FRAMEWORKS

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

#if !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX
Class<RCTComponentViewProtocol> BlurViewCls(void) __attribute__((used)); // 4
Class<RCTComponentViewProtocol> VibrancyViewCls(void) __attribute__((used)); // 4
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> RNDateTimePickerCls(void) __attribute__((used)); // 5
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> RNGoogleSigninButtonCls(void) __attribute__((used)); // 6
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif


#if !TARGET_OS_OSX && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> AutoLayoutViewCls(void) __attribute__((used)); // 9
Class<RCTComponentViewProtocol> CellContainerCls(void) __attribute__((used)); // 9
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> SkiaDomViewCls(void) __attribute__((used)); // 10
Class<RCTComponentViewProtocol> SkiaPictureViewCls(void) __attribute__((used)); // 10
#endif

Class<RCTComponentViewProtocol> LottieAnimationViewCls(void) __attribute__((used)); // 11
#if !TARGET_OS_OSX && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> RNDatePickerCls(void) __attribute__((used)); // 13
#endif


#if !TARGET_OS_OSX && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> FastImageViewCls(void) __attribute__((used)); // 15
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> RNVideoPlayerCls(void) __attribute__((used)); // 18
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

Class<RCTComponentViewProtocol> RNGestureHandlerButtonCls(void) __attribute__((used)); // 21
Class<RCTComponentViewProtocol> RNGestureHandlerRootViewCls(void) __attribute__((used)); // 21
#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> RNKlarnaCheckoutViewCls(void) __attribute__((used)); // 23
Class<RCTComponentViewProtocol> RNKlarnaPaymentViewCls(void) __attribute__((used)); // 23
Class<RCTComponentViewProtocol> RNKlarnaStandaloneWebViewCls(void) __attribute__((used)); // 23
#endif

#if !TARGET_OS_OSX && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> RNLinearGradientCls(void) __attribute__((used)); // 24
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> LiveStreamerCls(void) __attribute__((used)); // 25
#endif

#if !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV
Class<RCTComponentViewProtocol> LEGACY_RNCViewPagerCls(void) __attribute__((used)); // 27
Class<RCTComponentViewProtocol> RNCViewPagerCls(void) __attribute__((used)); // 27
#endif

#if !TARGET_OS_OSX && !TARGET_OS_VISION

#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> ProgressCircleCls(void) __attribute__((used)); // 29
#endif


#if !TARGET_OS_TV
Class<RCTComponentViewProtocol> RNCSafeAreaProviderCls(void) __attribute__((used)); // 31
Class<RCTComponentViewProtocol> RNCSafeAreaViewCls(void) __attribute__((used)); // 31
#endif

#if !TARGET_OS_OSX && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> RNSFullWindowOverlayCls(void) __attribute__((used)); // 32
Class<RCTComponentViewProtocol> RNSModalScreenCls(void) __attribute__((used)); // 32
Class<RCTComponentViewProtocol> RNSScreenContainerCls(void) __attribute__((used)); // 32
Class<RCTComponentViewProtocol> RNSScreenCls(void) __attribute__((used)); // 32
Class<RCTComponentViewProtocol> RNSScreenNavigationContainerCls(void) __attribute__((used)); // 32
Class<RCTComponentViewProtocol> RNSScreenStackHeaderConfigCls(void) __attribute__((used)); // 32
Class<RCTComponentViewProtocol> RNSScreenStackHeaderSubviewCls(void) __attribute__((used)); // 32
Class<RCTComponentViewProtocol> RNSScreenStackCls(void) __attribute__((used)); // 32
Class<RCTComponentViewProtocol> RNSSearchBarCls(void) __attribute__((used)); // 32
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION

#endif

Class<RCTComponentViewProtocol> RNSVGCircleCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGClipPathCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGDefsCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGEllipseCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGFeBlendCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGFeColorMatrixCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGFeFloodCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGFeGaussianBlurCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGFeMergeCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGFeOffsetCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGFilterCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGForeignObjectCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGGroupCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGImageCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGSvgViewCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGLinearGradientCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGLineCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGMarkerCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGMaskCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGPathCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGPatternCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGRadialGradientCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGRectCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGSymbolCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGTextCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGTextPathCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGTSpanCls(void) __attribute__((used)); // 34
Class<RCTComponentViewProtocol> RNSVGUseCls(void) __attribute__((used)); // 34
#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> VideoThumbnailsViewCls(void) __attribute__((used)); // 35
#endif

#if !TARGET_OS_TV && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> RNCWebViewCls(void) __attribute__((used)); // 36
#endif

#if !TARGET_OS_OSX && !TARGET_OS_TV && !TARGET_OS_VISION
Class<RCTComponentViewProtocol> WindowPortalViewCls(void) __attribute__((used)); // 37
#endif


#endif
#endif

#ifdef __cplusplus
}
#endif

#pragma GCC diagnostic pop

